# ----------------------- #
#      Main Configs       #
# ----------------------- #

url: http://www.devsh3th.github.io
title: Devansh Sheth
email: devanshsheth09@gmail.com
author: Devansh Sheth
description: "Devansh's Personal Page"

# ----------------------- #
#    Jekyll & Plugins     #
# ----------------------- #

# Build settings
markdown: kramdown
permalink: pretty
# Build sitemap
gems:
  - jekyll-sitemap

# ----------------------- #
#   3rd Party Settings    #
# ----------------------- #

social:
  - icon: github
    title: github
    url: https://github.com/Devsh3th  
  - icon: envelope-o
    title: email
    url: mailto:devanshsheth09@gmail.com
  - icon: linkedin
    title: linkedin
    url: https://www.linkedin.com/in/devanshsheth09/
  - icon: file-pdf-o
    title: Resume
    url: img/resume1.pdf
#  - icon: website
#    title: CV Lattes
#    url: http://lattes.cnpq.br/5399100590606067
#  - icon: twitter
#    title: twitter
#    url: https://twitter.com/danicassol

